"""Lead call-note recording repository — the sign-upload -> complete lifecycle.

Service-role writes only (0048 grants authenticated SELECT and nothing else), so
every mutation here runs behind api/lead_recordings.py, which is the authz
boundary. Mirrors media_repo.py's shape, scoped to one table with a real FK
(lead_id -> leads), so there is no polymorphic entity_exists() indirection here —
a lead's existence is checked directly by the route via lead_repo.get_lead.

Lifecycle, same meaning as media's:
    pending — a row + a signed upload URL were issued; the bytes may never arrive.
    ready   — bytes verified present in Storage (actual size, not the client's claim).
    failed  — the client reported/we detected a broken upload; GC target.
"""

from uuid import UUID

from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession

_FIELDS = (
    "id", "lead_id", "storage_key", "mime", "bytes", "duration_seconds",
    "note", "status", "created_by", "created_at", "uploaded_at",
)
_COLUMNS = ", ".join(_FIELDS)


async def create_pending(
    session: AsyncSession,
    *,
    recording_id: UUID,
    lead_id: UUID,
    storage_key: str,
    mime: str,
    created_by: UUID | None,
    note: str | None = None,
) -> dict:
    """Reserve a recording row before the bytes exist. The id is generated by the
    caller so it can be baked into the storage key."""
    result = await session.execute(
        text(
            "INSERT INTO lead_recordings (id, lead_id, storage_key, mime, note,"
            " status, created_by)"
            " VALUES (:id, :lead_id, :key, :mime, :note, 'pending', :by)"
            f" RETURNING {_COLUMNS}"
        ),
        {
            "id": str(recording_id), "lead_id": str(lead_id), "key": storage_key,
            "mime": mime, "note": note,
            "by": str(created_by) if created_by else None,
        },
    )
    return dict(result.mappings().one())


async def get_recording(session: AsyncSession, recording_id: UUID) -> dict | None:
    result = await session.execute(
        text(f"SELECT {_COLUMNS} FROM lead_recordings WHERE id = :id"),
        {"id": str(recording_id)},
    )
    row = result.mappings().first()
    return None if row is None else dict(row)


async def mark_ready(session: AsyncSession, recording_id: UUID, *, size_bytes: int) -> dict | None:
    """Flip pending -> ready. IDEMPOTENT: re-completing an already-ready row is a
    no-op that still returns the row (mirrors media_repo.mark_ready — a flaky phone
    network retrying the call must not surface as an error for succeeding twice)."""
    await session.execute(
        text(
            "UPDATE lead_recordings SET status = 'ready', bytes = :bytes, uploaded_at = now()"
            " WHERE id = :id AND status = 'pending'"
        ),
        {"id": str(recording_id), "bytes": size_bytes},
    )
    return await get_recording(session, recording_id)


async def mark_failed(session: AsyncSession, recording_id: UUID) -> None:
    await session.execute(
        text("UPDATE lead_recordings SET status = 'failed' WHERE id = :id AND status = 'pending'"),
        {"id": str(recording_id)},
    )


async def list_for_lead(
    session: AsyncSession, lead_id: UUID, *, ready_only: bool = True
) -> list[dict]:
    """One lead's recordings, newest first, joined with the uploader's name — answers
    "who recorded this call" without a second client-side fetch."""
    result = await session.execute(
        text(
            f"SELECT {', '.join('r.' + f for f in _FIELDS)}, sp.name AS uploaded_by_name"
            " FROM lead_recordings r"
            " LEFT JOIN salespersons sp ON sp.id = r.created_by"
            " WHERE r.lead_id = :lead_id"
            "   AND (:ready_only = false OR r.status = 'ready')"
            " ORDER BY r.created_at DESC"
        ),
        {"lead_id": str(lead_id), "ready_only": ready_only},
    )
    return [dict(r) for r in result.mappings().all()]
