"""Media registry repository — the sign-upload → complete → thumbnail lifecycle.

Service-role writes only (0025 grants authenticated SELECT and nothing else), so
every mutation here runs behind api/media.py, which is the authz boundary.

Lifecycle, and why each state exists:
    pending  — a row + a signed upload URL were issued; the bytes may never arrive.
               A gallery must not render these (broken tile forever).
    ready    — bytes verified present in Storage. `thumb_key` may still be NULL:
               the thumbnail is a best-effort worker job, and the gallery falls
               back to the full image. That is a designed state, not a failure.
    failed   — the client reported/we detected a broken upload; GC target.
"""

from uuid import UUID

from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession

_FIELDS = (
    "id", "entity_type", "entity_id", "kind", "storage_key", "thumb_key",
    "mime", "bytes", "status", "stage_code", "created_by", "created_at", "uploaded_at",
)
_COLUMNS = ", ".join(_FIELDS)


async def create_pending(
    session: AsyncSession,
    *,
    media_id: UUID,
    entity_type: str,
    entity_id: UUID,
    kind: str,
    storage_key: str,
    mime: str,
    created_by: UUID | None,
    stage_code: str | None = None,
) -> dict:
    """Reserve a media row before the bytes exist. The id is generated by the caller
    so it can be baked into the storage key."""
    result = await session.execute(
        text(
            "INSERT INTO media (id, entity_type, entity_id, kind, storage_key, mime,"
            " status, stage_code, created_by)"
            " VALUES (:id, :et, :eid, :kind, :key, :mime, 'pending', :stage, :by)"
            f" RETURNING {_COLUMNS}"
        ),
        {
            "id": str(media_id), "et": entity_type, "eid": str(entity_id), "kind": kind,
            "key": storage_key, "mime": mime, "stage": stage_code,
            "by": str(created_by) if created_by else None,
        },
    )
    return dict(result.mappings().one())


async def stage_code_for_entity(
    session: AsyncSession, entity_type: str, entity_id: UUID
) -> str | None:
    """The production stage a photo against this entity belongs to — a SERVER fact.

    Resolved here rather than accepted from the request: the PWA's screen can be minutes
    stale (a lead may have advanced the item from the dashboard meanwhile), and a photo
    filed under the wrong stage is misleading evidence rather than a cosmetic bug.

    A `production_event` carries its own stage, which is stronger than the item's current
    one — the event may already have moved the item on. Everything else (customer, order,
    product, workshop_transfer) has no stage, and gets None.
    """
    queries = {
        "order_item": "SELECT current_stage FROM order_items WHERE id = :id",
        "production_event": "SELECT stage_code FROM production_events WHERE id = :id",
    }
    sql = queries.get(entity_type)
    if sql is None:
        return None
    result = await session.execute(text(sql), {"id": str(entity_id)})
    row = result.first()
    return None if row is None or row[0] is None else str(row[0])


async def get_media(session: AsyncSession, media_id: UUID) -> dict | None:
    result = await session.execute(
        text(f"SELECT {_COLUMNS} FROM media WHERE id = :id"), {"id": str(media_id)}
    )
    row = result.mappings().first()
    return None if row is None else dict(row)


async def get_media_many(session: AsyncSession, media_ids: list[UUID]) -> list[dict]:
    """The rows for many ids in ONE query, so a gallery costs one round-trip.

    Missing and non-`ready` ids are simply absent from the result — a caller
    rendering twenty tiles must not lose the page because one row was GC'd. Order
    is not guaranteed; callers key by id.
    """
    if not media_ids:
        return []
    result = await session.execute(
        text(f"SELECT {_COLUMNS} FROM media WHERE id = ANY(:ids)"),
        {"ids": [str(m) for m in media_ids]},
    )
    return [dict(r) for r in result.mappings().all()]


async def mark_ready(session: AsyncSession, media_id: UUID, *, size_bytes: int) -> dict | None:
    """Flip pending → ready. IDEMPOTENT: re-completing an already-ready row is a
    no-op that still returns the row, because module 10's real-world failure mode is
    a flaky phone network retrying the call — a manager on a workshop floor must not
    see an error for succeeding twice."""
    await session.execute(
        text(
            "UPDATE media SET status = 'ready', bytes = :bytes, uploaded_at = now()"
            " WHERE id = :id AND status = 'pending'"
        ),
        {"id": str(media_id), "bytes": size_bytes},
    )
    return await get_media(session, media_id)


async def mark_failed(session: AsyncSession, media_id: UUID) -> None:
    await session.execute(
        text("UPDATE media SET status = 'failed' WHERE id = :id AND status = 'pending'"),
        {"id": str(media_id)},
    )


async def set_thumb_key(session: AsyncSession, media_id: UUID, thumb_key: str) -> bool:
    result = await session.execute(
        text("UPDATE media SET thumb_key = :tk WHERE id = :id RETURNING id"),
        {"tk": thumb_key, "id": str(media_id)},
    )
    return result.first() is not None


async def list_for_entity(
    session: AsyncSession, entity_type: str, entity_id: UUID, *, ready_only: bool = True
) -> list[dict]:
    """One entity's media, newest first, each row carrying its stage LABELS.

    The labels are joined here rather than looked up in the browser so a gallery header
    reads `Frame work · ફ્રેમ કામ` without the client shipping a second stage-defs fetch;
    `uploaded_by_name` answers the other question a photo raises ("who took this?").
    """
    result = await session.execute(
        text(
            f"SELECT {', '.join('m.' + f for f in _FIELDS)},"
            "       sd.label_en AS stage_label_en, sd.label_gu AS stage_label_gu,"
            "       sd.sort AS stage_sort, sp.name AS uploaded_by_name"
            " FROM media m"
            " LEFT JOIN production_stage_defs sd ON sd.code = m.stage_code"
            " LEFT JOIN salespersons sp ON sp.id = m.created_by"
            " WHERE m.entity_type = :et AND m.entity_id = :eid"
            "   AND (:ready_only = false OR m.status = 'ready')"
            " ORDER BY m.created_at DESC"
        ),
        {"et": entity_type, "eid": str(entity_id), "ready_only": ready_only},
    )
    return [dict(m) for m in result.mappings().all()]


async def entity_exists(session: AsyncSession, table: str, entity_id: UUID) -> bool:
    """Existence check for a polymorphic parent.

    `table` MUST come from services.media_entities.table_for() — a frozen whitelist.
    It is interpolated (a table name cannot be a bind parameter), so passing a
    request-derived string here would be SQL injection.
    """
    from ..services.media_entities import ENTITY_TABLES

    if table not in ENTITY_TABLES.values():
        raise ValueError(f"Refusing to query non-whitelisted table '{table}'")
    # A whitelisted entity type whose table has not shipped yet (e.g. 'delivery' →
    # `deliveries`, which lands in Phase 2C) must produce a clean "no such entity",
    # not an UndefinedTableError surfacing as a 500.
    exists = await session.execute(
        text("SELECT to_regclass(:qualified) IS NOT NULL"), {"qualified": f"public.{table}"}
    )
    if not exists.scalar_one():
        return False
    result = await session.execute(
        text(f"SELECT 1 FROM {table} WHERE id = :id"), {"id": str(entity_id)}
    )
    return result.first() is not None


async def customer_id_for_entity(
    session: AsyncSession, entity_type: str, entity_id: UUID
) -> str | None:
    """Resolve the customer a media entity ultimately belongs to, so the API can run
    the normal per-customer write check. None if the entity is missing."""
    queries = {
        "customer": "SELECT id FROM customers WHERE id = :id",
        "order": "SELECT customer_id FROM orders WHERE id = :id",
        "order_item": (
            "SELECT o.customer_id FROM order_items oi"
            " JOIN orders o ON o.id = oi.order_id WHERE oi.id = :id"
        ),
        "production_event": (
            "SELECT o.customer_id FROM production_events pe"
            " JOIN order_items oi ON oi.id = pe.order_item_id"
            " JOIN orders o ON o.id = oi.order_id WHERE pe.id = :id"
        ),
        "quotation_item": (
            "SELECT q.customer_id FROM quotation_items qi"
            " JOIN quotations q ON q.id = qi.quotation_id WHERE qi.id = :id"
        ),
        # 'product' is deliberately absent: a catalog photo belongs to no customer,
        # so it is gated on the admin role instead (api/media.py::_authorize_upload).
    }
    sql = queries.get(entity_type)
    if sql is None:
        return None
    result = await session.execute(text(sql), {"id": str(entity_id)})
    row = result.first()
    return None if row is None else str(row[0])


async def workshop_id_for_entity(
    session: AsyncSession, entity_type: str, entity_id: UUID
) -> str | None:
    """The workshop currently holding the order_item behind this entity, if any.
    Used to let a workshop manager attach photos to their OWN items and nothing else."""
    queries = {
        "order_item": "SELECT workshop_id FROM order_items WHERE id = :id",
        "production_event": (
            "SELECT oi.workshop_id FROM production_events pe"
            " JOIN order_items oi ON oi.id = pe.order_item_id WHERE pe.id = :id"
        ),
    }
    sql = queries.get(entity_type)
    if sql is None:
        return None
    result = await session.execute(text(sql), {"id": str(entity_id)})
    row = result.first()
    return None if row is None or row[0] is None else str(row[0])


async def has_active_personal_data_consent(session: AsyncSession, customer_id: str) -> bool:
    """DPDPA gate for customer-entity media (0025 header). Mirrors the shape of
    enforce_face_embedding_consent() (0004) at the API boundary."""
    result = await session.execute(
        text(
            "SELECT 1 FROM customers c JOIN consents co ON co.id = c.consent_id"
            " WHERE c.id = :id AND co.personal_data = true AND co.withdrawn_at IS NULL"
        ),
        {"id": str(customer_id)},
    )
    return result.first() is not None
